# FIRST LETS IMPORT NECESSARY PACKAGES 
from tkinter import *
# THE * SYMBOL MEANS EVERYTHING IN THE SPECIFIC PACKAGE


# CREATE A VARIABLE FOR THE Tkinter FUNCTION ( Tk() )

# NOW GIVE IT A TITLE
# LASTLY GIVE IT A HEIGHT AND WIDTH